### ISSUE TITLE
可能存在的超功率隐患

### ISSUE THREAD

**Issue by RealManShao** [Meta-Team/Meta-Infantry#30]
可能存在的超功率隐患
https://github.com/Meta-Team/Meta-Embedded/blob/2039ff803be48de96d243241d3656f5f4cde811a/dev/logic/chassis_logic.cpp#L157

`

void ChassisLG::CapacitorSetThread::main() {

    setName("capacitor_set_thread");
    while (!shouldTerminate()) {
        if ((float) Referee::power_heat.chassis_power_buffer - Referee::power_heat.chassis_power * 0.1 > 5.0) {
            CapacitorIF::set_power(95.0);
        } else {
            CapacitorIF::set_power((float) Referee::robot_state.chassis_power_limit * 0.8f);
        }
        sleep(TIME_MS2I(CAPACITOR_SET_INTERVAL));
    }
}

`

**Comment by liuzikai** [comment]
展开解释一下？
